---
# consul token acl
consul_acl_token: 09ad9b5e-7eb6-e49a-b7ec-9b6a21004c66
consul_configd_path: /etc/consul.d
# defaults file for consul-template
consul_template_version: "0.30.0"
consul_template_release: "consul-template_{{ consul_template_version }}_linux_amd64"
consul_template_archive_file: "{{ consul_template_release }}.zip"
consul_template_staging_area: "/tmp"
consul_template_download_url: "https://hashicorp-releases.yandexcloud.net/consul-template/{{ consul_template_version }}/{{ consul_template_archive_file }}"
consul_template_binary: consul-template
consul_template_home: /opt/consul-template
consul_template_use_config_dir: false
consul_template_config_file_template: consul-template.cfg.j2
consul_template_config_file: consul-template.hcl
consul_template_log_file: /var/log/consul-template
consul_template_log_level: "INFO"
consul_template_consul_server: "10.10.0.2"
consul_template_consul_port: "8500"
consul_template_use_systemd: true
consul_template_use_upstart: false
consul_template_use_initd: false
consul_template_initd_template: "consul-template.initd.sh.j2"
consul_template_template_files: [{src: "redis.ctmpl.j2"}] # {src: "redis.ctmpl.j2"}
consul_template_templates: [] # - [{name: "redis.ctmpl", dest: "/etc/consul.d/redis.json", cmd: "systemctl restart consul", perms: 0755, backup: false}]
consul_template_template_templates: [{name: "redis.ctmpl.j2", dest: "/etc/consul.d/redis.json", cmd: "systemctl restart consul", perms: 0755, backup: false}] # - {name: "template.ctmpl.j2", dest: "/path/on/disk/where/template/will/render", cmd: "optional command to run when the template is updated", perms: 0600, backup: true}
