---
all:
    vars:
      ansible_user: support
      ansible_password: elephant
    
    children:
      
      consul-server:
        hosts:
          consul:
            ansible_connection: ssh 
            ansible_host: 192.168.109.218
      
      consul-agent:
        children:
          redis-masters:
            hosts:
              redis-master:
                ansible_connection: ssh 
                ansible_host: 192.168.109.219
          
          redis-slave:
            hosts:
              redis-slave1:
                ansible_connection: ssh 
                ansible_host: 192.168.109.220
              redis-slave2:
                ansible_connection: ssh 
                ansible_host: 192.168.109.221
                