---
company:
  vars:
    ansible_user: support
    ansible_password: elephant
    
  children:
    consul-server:
      hosts:
        192.168.109.218:

      consul-agent:

      redis-master:
        hosts:
          192.168.109.219
      redis-slave:
        hosts:
          192.168.109.220:
            id: 1
          192.168.109.221:
            id: 2

