galaxy_info:
  author: Artemiy Zakharenko
  description: Install and configure consul agent
  company: Protei
  min_ansible_version: 2.9

  platforms:
  - name: Ubuntu
    versions: 
      - bionic
      - focal 
      - jammy
dependencies: []