---
- name: configure keepalived-master redis
  hosts: redis-masters
  become: yes
  gather_facts: yes

  roles:
    - role: keepalived-redis
  vars:
    keepalived_virtual_ip_address: "10.10.0.100"
    keepalived_state: 'MASTER'

- name: configure keepalived redis
  hosts: redis-slave
  become: yes
  gather_facts: yes

  roles:
    - role: keepalived-redis
  vars:
    keepalived_virtual_ip_address: "10.10.0.100"
    keepalived_state: 'BACKUP'
    