---
galaxy_info:
  author: Grig Gheorghiu
  description: Ansible role for installing and configuring consul-template
  license: license (Apache)
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  #  - lucid
  #  - maverick
  #  - natty
  #  - oneiric
  #  - precise
  #  - quantal
  #  - raring
  #  - saucy
  #  - trusty
  - name: Debian
    versions:
    - all
  #  - etch
  #  - lenny
  #  - squeeze
  #  - wheezy
  - name: EL
    versions:
    - 6
    - 7
  categories:
  - cloud
  - cloud:ec2
  - cloud:gce
  - cloud:rax
  - clustering
  - monitoring
  - networking
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
